### ISSUE TITLE
Issue with Biopython versions

### ISSUE THREAD

**Issue by timyerg** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#14]
Dear Tiago Antao!
I would like to report several issues with Biopython versions.
I am running Ubuntu 20.04 and Python 3.7 (anaconda).
In chapter 7, "Intro.ipynb" notebook, when I am using  Biopython 1.76 or lower and launch the next cell:
`sp_rec= SwissProt.read(handle)`
It is giving me an error:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-f785d9884f77> in <module>
----> 1 sp_rec= SwissProt.read(handle)

~/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in read(handle)
    149     Returns a Record() object.
    150     """
--> 151     record = _read(handle)
    152     if not record:
    153         raise ValueError("No SwissProt record found")

~/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in _read(handle)
    253             _read_kw(record, value)
    254         elif key == "FT":
--> 255             _read_ft(record, line)
    256         elif key == "SQ":
    257             cols = value.split()

~/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in _read_ft(record, line)
    592         description = line[29:70].rstrip()
    593     if not name:  # is continuation of last one
--> 594         assert not from_res and not to_res, line
    595         name, from_res, to_res, old_description, old_ft_id = record.features[-1]
    596         del record.features[-1]

AssertionError:                 /note="Ribonucleoside-diphosphate reductase subunit M2 B"
```
If I am updating to Biopython 1.77, cell above is running succesfully, but I am still getting error in the last cell:
```
done_features = set()
print(len(sp_rec.features))
for feature in sp_rec.features:
    if feature[0] in done_features:
        continue
    else:
        done_features.add(feature[0])
        print(feature)
print(len(sp_rec.cross_references))
per_source = defaultdict(list)
for xref in sp_rec.cross_references:
    source = xref[0]
    per_source[source].append(xref[1:])
print(per_source.keys())
done_GOs = set()
print(len(per_source['GO']))
for annot in per_source['GO']:
    if annot[1][0] in done_GOs:
        continue
    else:
        done_GOs.add(annot[1][0])
        print(annot)
```
out
```
50
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-72ef20db465f> in <module>
      2 print(len(sp_rec.features))
      3 for feature in sp_rec.features:
----> 4     if feature[0] in done_features:
      5         continue
      6     else:

TypeError: 'FeatureTable' object is not subscriptable
```
I can run this cell by deleting 2 `[0]` in this part:
```
    if feature[0] in done_features:
        continue
    else:
        done_features.add(feature[0])
```

Next issue is in the "PDB.ipynb" notebook: with Biopython 1.77 i am getting an error in cell:
```
from Bio.SeqIO import PdbIO, FastaIO

def get_fasta(pdb_file, fasta_file, transfer_ids=None):
    fasta_writer = FastaIO.FastaWriter(fasta_file)
    fasta_writer.write_header()
    for rec in PdbIO.PdbSeqresIterator(pdb_file):
        if len(rec.seq) == 0:
            continue
        if transfer_ids is not None and rec.id not in transfer_ids:
            continue
        print(rec.id, rec.seq, len(rec.seq))
        fasta_writer.write_record(rec)
        
get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])
get_fasta(open('pdb1olg.ent'), open('1olg.fasta', 'w'), transfer_ids=['1OLG:B'])
get_fasta(open('pdb1ycq.ent'), open('1ycq.fasta', 'w'), transfer_ids=['1YCQ:B'])
```
out
```
1TUP:B SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNT 219
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-8ecf92753ac9> in <module>
     12         fasta_writer.write_record(rec)
     13 
---> 14 get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])
     15 get_fasta(open('pdb1olg.ent'), open('1olg.fasta', 'w'), transfer_ids=['1OLG:B'])
     16 get_fasta(open('pdb1ycq.ent'), open('1ycq.fasta', 'w'), transfer_ids=['1YCQ:B'])

<ipython-input-10-8ecf92753ac9> in get_fasta(pdb_file, fasta_file, transfer_ids)
     10             continue
     11         print(rec.id, rec.seq, len(rec.seq))
---> 12         fasta_writer.write_record(rec)
     13 
     14 get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])

~/anaconda3/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py in write_record(self, record)
    303     def write_record(self, record):
    304         """Write a single Fasta record to the file."""
--> 305         assert self._header_written
    306         assert not self._footer_written
    307         self._record_written = True

AttributeError: 'FastaWriter' object has no attribute '_header_written'
```
But everything is working with Biopython 1.76.

I am still going through the book, and will add more issues  with Biopython versions here if I will encounter any

**Comment by tiagoantao** [comment]
The book was written with an older version of biopython and I am not expecting it to be able to run with all future versions of it.
There are 2 problems:

- Biopython does not follow semantic versioning. So its difficult to pin down where code should work
- I did not fix a version of Biopython - which was a mistake of my part

I think I used 1.70, and its great that you found out that the code works with 1.76.
But as time goes by, it is expected that the code will stop working with newer versions of biopython (and other software)
